name: Flutter build Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        flutter-channel: [ 'stable', 'beta' ]
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Cache gradle, wrapper and buildSrc
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter-channel }}
  
      - name: Print Dart SDK version
        run: dart --version
        
      - name: Print Flutter SDK version
        run: flutter --version
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Format code
        run: flutter format lib --set-exit-if-changed
        
#       - name: Analyze
#         run: flutter analyze lib
      
#       - name: Gen code
#         run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
      - name: Build APK
        run: flutter build apk --no-shrink
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/app/outputs/apk/release/app-release.apk
